import matplotlib.pyplot as plt
import numpy as np


fig = plt.figure()
ax1 = fig.add_subplot(111)
plt.xlim(0, 20)
plt.ylim(0, 30)
plt.yticks(xrange(0, 30))
plt.xticks(xrange(0, 30))
# ax2 = fig.add_subplot(212)
x1_points = xrange(0, 9)
y1_points = xrange(0, 9)
x2_points = xrange(0, 10)
y2_points = xrange(1, 11)
p = ax1.plot(x1_points, y1_points, x2_points, y2_points, 'r')
# p = ax2.plot(x2_points, y2_points, 'g')
# p = ax.plot(x_points, np.sin(x_points), 'b')
ax1.set_xlabel('x-points')
ax1.set_ylabel('y-points')
ax1.set_title('Simple XY point plot')
# ax2.set_xlabel('x-points')
# ax2.set_ylabel('y-points')
# ax2.set_title('Simple XY point plot')
plt.show()